name: hello
description: A new Flutter project.


flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  build_web_compilers: any

environment:
  sdk: '>=2.0.0-dev.48 <2.0.0'